### ISSUE TITLE
Package as PHAR

### ISSUE THREAD

**Issue by igorw** [igorw/composer-yaml#3]
So people don't add it as a dep to their projects, see #2.

**Comment by c33s** [comment]
do you have any timeframe for this? (just interested)

**Comment by igorw** [comment]
Not high prio, feel free to make a PR based on the silex phar compiler.

**Comment by srosato** [comment]
I have made a very simple pull request to resolve this using the Box project. https://github.com/igorw/composer-yaml/pull/7

**Comment by DracoBlue** [comment]
Ticket is resolved, isn't it? @igorw

**Comment by igorw** [comment]
yup, thanks
